# Generated by Django 3.1.7 on 2021-02-20 11:54

import Task_App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_App', '0002_auto_20210220_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='firstName',
            field=models.CharField(max_length=100, validators=[Task_App.validators.Namevalidator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='lastName',
            field=models.CharField(max_length=100, validators=[Task_App.validators.Namevalidator]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=20, validators=[Task_App.validators.PasswordValidator]),
        ),
    ]
