# Generated by Django 3.1.7 on 2021-02-20 12:53

import Task_App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_App', '0003_auto_20210220_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=100, validators=[Task_App.validators.Namevalidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=100, validators=[Task_App.validators.Namevalidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(validators=[Task_App.validators.MobileNoValidator]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=20, validators=[Task_App.validators.PasswordValidator]),
        ),
    ]
